name: ChatGPT PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  chatgpt_review:
    runs-on: ubuntu-latest

    steps:
      - name: ChatGPT Integration
        uses: kxxt/chatgpt-action@v0.3
        with:
          number: ${{ github.event.pull_request.number }}
          sessionToken: ${{ secrets.CHATGPT_SESSION_TOKEN }}
          split: 'yolo'
